name: Destroy Terraform in AWS

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      aws_region: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Move backend.tf
        run: cp ./backend.tf ./terraform

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.aws_region }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init -migrate-state

      - name: State list
        run: terraform state list

      - name: Destroy Terraform
        working-directory: ./terraform
        run: terraform destroy -auto-approve
