name: Prueba simultanea

on:
  workflow_dispatch:

jobs:
  deploy-with-dynamo:
    runs-on: ubuntu-latest

    env:
      aws_region: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.aws_region }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download Terraform State
        run: aws s3 cp s3://ia-automatizacion-jose-manuel-bucket/terraform.tfstate prueba/terraform.tfstate

      - name: Initialize Terraform
        working-directory: ./prueba
        run: terraform init

      - name: Terraform plan
        working-directory: ./prueba
        run: terraform plan

      - name: Terraform apply
        working-directory: ./prueba
        run: terraform apply -auto-approve


  deploy-with-dynamo-2:
    runs-on: ubuntu-latest

    env:
      aws_region: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.aws_region }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download Terraform State
        run: aws s3 cp s3://ia-automatizacion-jose-manuel-bucket/terraform.tfstate prueba/terraform.tfstate

      - name: Initialize Terraform
        working-directory: ./prueba
        run: terraform init

      - name: Terraform plan
        working-directory: ./prueba
        run: terraform plan

      - name: Terraform apply
        working-directory: ./prueba
        run: terraform apply -auto-approve