name: Prueba simultanea

on:
  workflow_dispatch:

jobs:
  move-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Move files for deploy backend
        run: | 
          cp ./terraform/main.tf ./prueba/main.tf
          cp ./terraform/variables.tf ./prueba/variables.tf
          cp ./terraform/terraform.tfvars ./prueba/terraform.tfvars

  deploy-with-dynamo:
    runs-on: ubuntu-latest
    needs: move-files

    env:
      aws_region: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.aws_region }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        working-directory: ./prueba
        run: terraform init

      - name: Terraform plan
        working-directory: ./prueba
        run: terraform plan

      - name: Terraform apply
        working-directory: ./prueba
        run: terraform apply -auto-approve


  deploy-with-dynamo-2:
    runs-on: ubuntu-latest
    needs: move-files

    env:
      aws_region: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.aws_region }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        working-directory: ./prueba
        run: terraform init

      - name: Terraform plan
        working-directory: ./prueba
        run: terraform plan

      - name: Terraform apply
        working-directory: ./prueba
        run: terraform apply -auto-approve